version: '3'
services:
  angular:
    build: .
    image: akirakoyasu/dev-study-ng-animation
    volumes:
      - "${PWD}:/var/lib/ng"
    ports:
      - "14200:4200"
    working_dir: /var/lib/ng/practice-angular-animations
    command:
      - ng
      - serve
      - -host
      - 0.0.0.0
